// swift-tools-version: 6.0
//
// libghostty — Ghostty's terminal engine (renderer + input + parser +
// surface C API) packaged as a SwiftPM binary dependency for
// Apple-platform apps.
//
// The product `GhosttyKit` is the upstream module name (umbrella
// header `ghostty.h`), kept verbatim so consumers' `import GhosttyKit`
// is unchanged.
//
// The companion product `GhosttyKitResources` ships libghostty's
// runtime resource tree (terminfo sentinel + shell-integration +
// themes) inside the package via `Bundle.module`, so consumers need
// no separate release asset and no local Ghostty build to obtain it.
// The tree is committed under `Sources/GhosttyKitResources/Resources`
// and regenerated by `scripts/build-xcframework.sh` on every build.
//
// The xcframework is built from the pinned Ghostty submodule
// (`vendor/ghostty`) by `scripts/build-xcframework.sh` and published
// as a GitHub release asset by `scripts/release.sh`.
// `binaryTarget(url:checksum:)` makes SwiftPM fetch + cache it at
// resolution time, so consuming a tagged version needs no zig, no
// Ghostty source, no local build.
//
// RELEASE PROCEDURE (the url/checksum below are per-tag — see
// README.md "Cutting a release"): for tag vX.Y.Z `scripts/release.sh`
// builds the xcframework, uploads `GhosttyKit.xcframework.zip` to the
// vX.Y.Z release, and prints the `swift package compute-checksum`
// value; that exact url + checksum are committed on the release tag.

import PackageDescription

// Per-release pin. Until the first release is cut these are
// placeholders and `swift build` will fail with a checksum mismatch
// by design — see README.md.
// `repoSlug` is "<owner>/<repo>" — set once to your GitHub slug.
// release.sh reads this and the tag to build the asset URL; it does
// not guess it.
let repoSlug = "sethdeckard/libghostty-spm"
let releaseTag = "v0.1.1"
let checksum = "c00624be664c49a9e9353fc785b7bfef53d4e218abb832a69f0aa7a33721bc7f"
let assetURL =
    "https://github.com/" + repoSlug + "/releases/download/"
    + releaseTag + "/GhosttyKit.xcframework.zip"

let package = Package(
    name: "Libghostty",
    platforms: [
        .macOS(.v14),
    ],
    products: [
        .library(name: "GhosttyKit", targets: ["GhosttyKit"]),
        .library(
            name: "GhosttyKitResources",
            targets: ["GhosttyKitResources"]
        ),
    ],
    targets: [
        .binaryTarget(
            name: "GhosttyKit",
            url: assetURL,
            checksum: checksum
        ),
        // `.copy` (not `.process`): the tree is hundreds of theme
        // files with spaces/parens in their names plus compiled
        // terminfo — it must ship byte-for-byte, not be run through
        // SwiftPM's resource processor.
        .target(
            name: "GhosttyKitResources",
            resources: [
                .copy("Resources"),
            ]
        ),
    ]
)
